### ISSUE TITLE
Fix backdrop right width calculation

### ISSUE THREAD

**Issue by thenewbeat** [IGreatlyDislikeJavascript/bootstrap-tourist#10]
The original calc is not taking into account the anchor elements left offset, causing the right backdrop to go off the page, possibly throwing off the page's layout.

**Comment by thenewbeat** [comment]
`$backdropRight.width(docWidth - (elementData.width + elementData.offset.left));`

**Comment by IGreatlyDislikeJavascript** [comment]
Your pull is merged, thank you for the fix!
