### ISSUE TITLE
ERROR TypeError: Cannot read property 'buttonTexts' of undefined

### ISSUE THREAD

**Issue by DancingDad** [IGreatlyDislikeJavascript/bootstrap-tourist#14]
I use bootstrap tour in my angular/bootstrap project (you can see it here if you like)
https://refavo-test.firebaseapp.com/

I have experienced quite a few issues with css conflicts between bootstrap tour and bootstrap v4 and have a new one today with the collapse bootstrap feature. I am hoping that your fork and updates are able to resolve this for bootstrap 4.0 as I do like the bootstrap tour functionality.

I have followed your instructions but am getting the following runtime error in console when attempting to create the new Tour object:

``ERROR TypeError: Cannot read property 'buttonTexts' of undefined``

On investigation it tells me that in bootstrap-tourist.js, this value is not defined 
` prevButton: this._options.localization.buttonTexts.prevButton||"Prev",`

It is worth noting that I do not add the steps on creation of the Tour object but do this afterwards via calls to the `addStep` method.

**Comment by IGreatlyDislikeJavascript** [comment]
Hi, thanks for your report and for using Tourist!

Which browser are you using when you get that error? I bet it's IE... The issue is that your browser is rejecting the js that sets a default button text due to a parent object not existing - I'm guessing Chrome creates the objects, but your browser isn't doing so.

Please can you try adding the following code at line 687 of bootstrap-tourist.js:

```
      // CUSTOMIZABLE TEXTS FOR BUTTONS
      // set defaults
      this._options.localization = {}; // add this line
      this._options.localization.buttonTexts = {}; // add this line
      objTemplatesButtonTexts = ...leave the rest of the code unchanged
```

If that doesn't work for you, you can simply change objTemplatesButtonTexts to explicitly assign the values, i.e. change line 689 onwards to:

```
      objTemplatesButtonTexts = {
        prevButton: "Prev",
        nextButton: "Next",
        pauseButton: "Pause",
        resumeButton: "Resume",
        endTourButton: "End Tour"
      };
```

I'd like to fix this properly though, so please do let me know what browser you're using. Thank you!

**Comment by DancingDad** [comment]
Hi, I am using Chrome.  Version 75.0.3770.100 (Official Build) (64-bit)
I will try these fixes now. Thanks!

**Comment by DancingDad** [comment]
The first fix worked! Thanks very much for that. I like the new look as well. Very cool.

**Comment by DancingDad** [comment]
ok. perhaps jumped the gun on the "fix worked". The first tour shows up. I can see it us step 1/8. The progress bar is correct. However, the buttons do not do anything. Neither the Next or End Tour buttons.  (the previous button is correctly disabled. There are no errors in the console.  I will investigate and raise an another error report if needed. Thanks again.

**Comment by DancingDad** [comment]
Found the issue.. removing the "name:"  attribute added when initialising the Tour object fixed it. I did not have this attribute before but thought it something needed. Perhaps if it is to do with the generation of the local variables to persist the tours current state i.e. progress, end state?

**Comment by IGreatlyDislikeJavascript** [comment]
That's very strange. Just so I'm clear, you're saying that removing the name: option from the tour options fixes the original TypeError you were getting - without using the extra lines of object setup I posted?

The name option is used for a couple of things: pseudo classes for selectors to uniquely identify tour elements, local storage state persistence, triggers etc. 

But none of those affect the piece of code you had the original problem with. I'm using Chrome as well, and I don't get the typerror issue. So I'm very confused!

The fact that you said this originally:

> I have experienced quite a few issues with css conflicts between bootstrap tour and bootstrap v4 

makes me suspect there's something else going on here as there's no conflicts between Tourist css and BS4 css. Removing the name property would change some of the pseudo css selectors created by Tourist code, which may in turn have some relation to the "css conflicts" you've mentioned. 

I think we need to dive into these issues in more detail to figure out where they are...

**Comment by thenewbeat** [comment]
@DancingDad I just implemented this library into my Angular 8 project and ran across the same issue. 

when compiling the `bootstrap-tourist.js` errors here: 
```
// CUSTOMIZABLE TEXTS FOR BUTTONS
      // set defaults
      objTemplatesButtonTexts = {
        prevButton: this._options.localization.buttonTexts.prevButton||"Prev",
        nextButton: this._options.localization.buttonTexts.nextButton||"Next",
        pauseButton: this._options.localization.buttonTexts.pauseButton||"Pause",
        resumeButton: this._options.localization.buttonTexts.resumeButton||"Resume",
        endTourButton: this._options.localization.buttonTexts.endTourButton||"End Tour",    
      }
```
You have to manually tell your `Tour` instance which button labels to use, but the instructions for doing so in the documentation don't work, so I had to modify them like so: 

```
this.tour = new Tour({
      framework: "bootstrap4",
      steps: [ ...  ],
      localization: {
        // define your button text here
        buttonTexts: {
          prevButton: "Prev", 
          nextButton: "Next",
          pauseButton: "Pause",
          resumeButton: "Continue",
          endTourButton: "End"
        }
      }
    });
```

**Comment by DancingDad** [comment]
Sorry, I muddled issues on the same thread (should have created a separate issue)
1.  Adding this fixed the type error - SOLVED
```  
    // set defaults
    this._options.localization = {}; // add this line
    this._options.localization.buttonTexts = {}; // add this line
```

**Comment by IGreatlyDislikeJavascript** [comment]
@dancingdad @thenewbeat thanks for confirming the fix. I'm going to reopen this issue until I fix it in the repo, probably tomorrow.

**Comment by DancingDad** [comment]
@thenewbeat  I see, passing the buttontexts attribute in and defining the text of the buttons was another way of solving this. Nice one. I guess it is now for @IGreatlyDislikeJavascript  to decide which is the best approach.

**Comment by bardware** [comment]
I noticed that behaviour in the past week and wanted to take this evening to report it and maybe offer a PR. Good to see you are addressing the issue, already!
If I don't pass the button texts in the call to `new Tour` , I get the error in line 690 because everything is undefined. My fix looked like
```
// add this line at around 654
localization: {
    buttonTexts = {}
},
```

I secondly add the lines from your documentation to my call to `new Tour` 
```
localization:
	{
		buttonTexts.prevButton: "Back",
		buttonTexts.nextButton: "Go",
		buttonTexts.pauseButton: "Wait",
		buttonTexts.resumeButton: "Continue",
		buttonTexts.endTourButton: "Ok, enough"
	}
```
but my JavaScript editor already complains because of invalid syntax. Fix looks like
```
	localization: {
		buttonTexts: {
			prevButton: 'Back',
			nextButton: 'Go',
			pauseButton: 'Wait',
			resumeButton: 'Continue',
			endTourButton: 'Ok, enough'
		}
	}
```

I wanted to try that out before reporting because I was unsure if my browser was the culprit. I had worked in IE 11 but now I see it doesn't work in Chrome, too.

Again, thanks for keeping the project alive,
Bernhard

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks everyone. I've uploaded a new commit that changes the way the localization/buttontexts works, to hopefully fix this issue and to also add a little future proofing for localization. 

Usage appears no different - i.e.: as per thenewbeat and bardware have posted above.

You can also only specify the button texts you want to change, and the other buttons will retain their defaults. For example:
```
localization:
{
	buttonTexts: { endTourButton: 'Adios muchachos'	} 
}
```

However, I'm still not sure why the previous code worked fine on my systems (and for the original pull creator vneri), but threw errors on everyone else's. Interested to hear if anyone has an explanation for that.

Thanks all!

**Comment by vneri** [comment]
Hi all, thanks for finding & fixing this
I am not sure, why I didn't work, but apparently it is because the object was not defined, when it is not passed.

BTW: where can we have a chat/conversation on the project? I wanted to discuss an idea (a tour-manager) - shall I just create an "issue"? (didn't like "issue" as placeholder for idea...)

**Comment by IGreatlyDislikeJavascript** [comment]
Hi vneri, I have no idea why your code worked perfectly for you and I, but threw errors for others. If anyone figures that out I'd love to know.

> where can we have a chat/conversation on the project

I'm not a github expert (I'm barely a novice!) but I think that opening an "issue" is the right approach. We can discuss your idea in the thread then, when you're ready to put some code together, we can continue discussing and reviewing in a pull.

Unless anyone else has a more appropriate suggestion?

**Comment by vneri** [comment]
Thanks for the feedback, I've started a new issue
I think we could try to use https://gitter.im/?

**Comment by scriptsure** [comment]
@DancingDad I was trying to get tourist to work with angularjs 1.7. How did you get it to work? In terms of injection of module and use of service in controllers?

**Comment by DancingDad** [comment]
@scriptsure I do not use AngularJS. I use Angular.

For Angular. In my component (
in this case a Navbar, as the tour is launched from a Bootstrap style Navbar menu)

In my navbarComponent.ts

imports...
...
**declare var Tour: any;**

export class navbarComponent implements OnInit, AfterViewInit {
....
**tour: any;**

// Create a new tour
ngAfterViewInit() {
    **this.tour = new Tour({
        debug: false,	// you may wish to turn on debug for the first run through
        framework: 'bootstrap4', // set Tourist to use BS4 compatibility
    });**

// Add the tour steps
**this.tour.addStep({
      element: '#element123',  // Mapped to element in DOM
      title: 'Test',
      content: 'This is a sample tour',
      placement: 'top',
    });**
}

// Called on menu selection
startATour() {
    // Initialize the tour
    **this.tour.restart();**
    // Start the tour Pass true to force the start.
    **this.tour.start(true);**
  }


In my navbarComponent.html
...
**<a id="startTourId" class="dropdown-item" (click)="startATour()">Start a tour</a>**
...

In my angular.json I have:
"styles": [
....
....
**"node_modules/bootstrap-tour/build/css/bootstrap-tourist.css"**
]

"scripts": [  
....
....
**"node_modules/bootstrap-tour/build/js/bootstrap-tourist.js"**
]

**Comment by scriptsure** [comment]
@DancingDad sorry late on this... I think the thing that I am not sure about is how do you inject into your controller... in your case import. I guess I would not be able to use it inside of a controller on angularjs. You agree?

**Comment by IGreatlyDislikeJavascript** [comment]
@scriptsure have you tried searching for a solution to this, but using Bootstrap Tour? Tour was/is very widely used, and a quick Google shows lots of angular and Tour discussions. If someone has solved it for Tour, the same solution should work for Tourist. As before, sorry I don't know how to help you with this but I'm happy to make changes to code if needed, when I can.
