### ISSUE TITLE
Tourist Documentation improvements

### ISSUE THREAD

**Issue by IGreatlyDislikeJavascript** [IGreatlyDislikeJavascript/bootstrap-tourist#15]
Currently, users of this fork must refer to the original Tour docs and website, then read through the lengthy comments at the top of the bootstrap-tourist.js / in the Tourist readme to find out what features, fixes and other points are included and are different to Tour. This is causing confusion!

A proper set of documentation specifically for Tourist is required. 

If anyone would like to help with this, nominally by taking the Tour docs and incorporating the Tourist readme, it would be appreciated!

**Comment by thenewbeat** [comment]
I can work on this. I'll copy over the original documentation from Bootstrap Tour (since it's formatted well) and update it based on all the changes that have been made.

**Comment by IGreatlyDislikeJavascript** [comment]
Fantastic, thank you.

**Comment by danielmoralesp** [comment]
Hi @IGreatlyDislikeJavascript just here to thank you for this great job! tons of bugs in the original tour  :(

**Comment by IGreatlyDislikeJavascript** [comment]
Thank you! But it's not just me any more, there's a bunch of other people who have also contributed to Tourist, so it's a team effort. I've tried to credit everyone in the read me and js comments.

Maybe we could entice you as well? ;-)

**Comment by IGreatlyDislikeJavascript** [comment]
Hey @thenewbeat, have you had a chance to update the docs? I think we're close to a v0.3.0 release with the new backdrop, so will have a few extra options to add to the docs.

Thanks!

**Comment by IGreatlyDislikeJavascript** [comment]
Documentation in the repo!
