### ISSUE TITLE
IE says ')' is missing 

### ISSUE THREAD

**Issue by Syiana** [IGreatlyDislikeJavascript/bootstrap-tourist#2]

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for the report. Please can you provide me with a bit more information? Does IE tell you what line of code this error occurs on?

If you're unsure how to find out some more information, please see here:
https://stackoverflow.com/questions/10191099/debugging-javascript-in-ie

---
Please note that Bootstrap Tourist is in development and may contain bugs. All bug reports, fixes, pull requests and suggestions are very appreciated. However if you're uncomfortable with this and come across an error or issue, please consider using [Bootstrap Tour](https://github.com/sorich87/bootstrap-tour) instead

**Comment by bduran82** [comment]
The problem is that IE doesn't support ES6 default parameters used in some functions like:

```
...
Tour.prototype._showNextStep = function (skipOrphan = false) {
...
```

**Comment by IGreatlyDislikeJavascript** [comment]
@bduran82 got it, thank you for the explanation. I didn't realize people still used IE ;-) . I'll change the way I handle default params to make them IE compatible, and publish a new version shortly.

**Comment by gsrafael01** [comment]
@IGreatlyDislikeJavascript You could use Babel to handle compatibility with older browsers instead of changing your code. That way, you can write your code using ES6, but ship it to incompatible browsers with Babel.

**Comment by IGreatlyDislikeJavascript** [comment]
Thank you, I'll take a look at that. One of the primary concerns with Tourist is keeping it as lean and close to original Tour as possible to facilitate a future merge-back, so will also need to keep that in mind.

**Comment by IGreatlyDislikeJavascript** [comment]
Latest commit removes reliance on default params to solve this issue.

https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/commit/286e78234a562854317f7cfbfdc01c617e5e099c
