### ISSUE TITLE
$modalObject not defined

### ISSUE THREAD

**Issue by Sell24** [IGreatlyDislikeJavascript/bootstrap-tourist#35]
Hi,

I downloaded the latest release and, in full disclosure, am trying to get a basic tour as shown in the example to work in VueJS built on BS4 .

However, I ran into a "Uncaught ReferenceError: $modalObject is not defined" error at line 1253. 
In order to fix it, I had to declare it within the Tour.prototype.showStep function.

I haven't quite got it to work yet, as it is failing in the _scrollIntoView function, but if I can't figure out why I will ask in a separate issue.

**Comment by Sell24** [comment]
Just in case anyone reads my last sentence, where I could not get it to work with BS4. BS4 uses the slim version of jQuery by default. In order to use the animation features you must change to the full (minified) version.

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for finding this one too. This is already fixed in the unstable/new-backdrop, which will become main branch shortly, so a fix is imminent.

**Comment by IGreatlyDislikeJavascript** [comment]
v0.3.0 uploaded into master branch, this issue should be fixed.
