### ISSUE TITLE
Uncaught ReferenceError: rslt is not defined

### ISSUE THREAD

**Issue by Sell24** [IGreatlyDislikeJavascript/bootstrap-tourist#36]
Similar to the #35 , the variable rslt is not defined in the following function.
Tour.prototype._showNextStep = function (skipOrphan)

**Comment by Sell24** [comment]
The same variable is missing in Tour.prototype._showPrevStep = function (skipOrphan) 

Despite these minor issue I do want to thank you for the work you put into improving the original.

**Comment by IGreatlyDislikeJavascript** [comment]
Thank you for spotting that, I've fixed it in the development version now - which will become the main branch shortly.

**Comment by IGreatlyDislikeJavascript** [comment]
v0.3.0 uploaded into master branch, this issue should be fixed.
