### ISSUE TITLE
reflexOnly: true allow proceed if using keyboard arrows

### ISSUE THREAD

**Issue by sdlins** [IGreatlyDislikeJavascript/bootstrap-tourist#45]
Hi, 

The option `reflexOnly: true` works fine when using mouse clicks but fails to prevent to proceed when using keyboard (arrow right) in that case it will proceed normally.

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for the report, this should be easy to fix via the keyboard handler. I'll update the repo with a fix shortly (next couple of days).

**Comment by IGreatlyDislikeJavascript** [comment]
Repo updated, this should now be fixed. I'll leave it open for a few days for you to confirm and close. Thanks!

**Comment by sdlins** [comment]
@IGreatlyDislikeJavascript sorry, I still haven't had time to check these changes! But we can close this, I think. When I can test it, I will give you a feedback here. Thank you too.
