### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bardware** [IGreatlyDislikeJavascript/bootstrap-tourist#6]
Hi,

do you publish this library under a certain license?
If you have no preference, than you can maybe add MIT license as on of the most free licences available.

Thank you for your work,
Bernhard

**Comment by IGreatlyDislikeJavascript** [comment]
Hi, thanks for the question. Tourist is indeed published under MIT license, please see the very bottom of the readme. 

This matches the original Tour license as well, for continuity and easy upgrading.

**Comment by bardware** [comment]
Github woul show that prominently if there's a `LICENSE` file in the root folder. :)
Thanks for the answer!
