### ISSUE TITLE
Next button partially working at the end of the tour.

### ISSUE THREAD

**Issue by kwojcicki** [IGreatlyDislikeJavascript/bootstrap-tourist#61]
When you are at the end of the tour (i.e. at the final step) the next button has the disabled css, but is still very much clickable. 

If clicked the tour gets into a weird state where it attempts to move to a null step. 

![bug_tour](https://user-images.githubusercontent.com/2487946/90908385-4deff500-e3a2-11ea-884a-3c9cb59119f3.gif)

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for reporting this, and the gif is very helpful. Please can you confirm if your issue is the same as this one?

https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/issues/54

**Comment by kwojcicki** [comment]
Yes your right! My apologies I will close this ticket in favor of that 😄 Thanks for the great library btw.
